name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  call-reusable-workflow:
    uses: intisy/workflows/.github/workflows/assign.yml@main
    with:
      assignees: "intisy"
    secrets:
      envPAT: ${{ secrets.PAT }}